source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"
use_frameworks!

target 'PaymentSDK' do
 pod 'CryptoSwift'
 pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git'
 pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
 pod 'OpenSSL'
end

target 'WalletDemo' do
 pod 'CryptoSwift'
 pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git'
 pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
 pod 'OpenSSL'
end

target 'CardDemo' do
 pod 'CryptoSwift'
 pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git'
 pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
 pod 'OpenSSL'
end

target 'PaymentSDKTests' do
 pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git'
end

