source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"
use_frameworks!

target 'PaymentDemo' do

pod 'CryptoSwift', '0.6.9'
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '4.4.0'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :tag => '3.1.4'
pod 'OpenSSL-Universal', '1.0.2.10'

end

